#!/bin/sh

os=`uname`;

case $os in
#SunOS)
#	compl=CC;;
Linux)
    Xtra=bin/Linux/dso_handle.o
	compl=g++;;
*)
	echo "unknown operating system"
	exit 1;;	
esac

if ! make COMPL=$compl OS=$os all $Xtra; then
	echo; echo "*** MakeMake/install failed ***"; echo;
	exit 1;
fi

cd ..
os=`uname`
for dir in include bin lib bin/$os lib/$os out
do
	if [ ! -d $dir ]; then
		mkdir $dir
	fi
done
cp -r MakeMake/bin/$os bin
if [ ! -d include/backward ]; then
    #cd include
    #ln -s ../backward .
    cp -r backward include
fi
