#!/bin/sh


OS=`uname -s`

case $OS in
Linux)
	COMPL=g++;;
*)
	echo "\nsystem $OS not known\n"
	exit 1;;	
esac

make Cleanup || {
    echo make Cleanup failed
    exit 1
}

echo
echo "***** Running make    *****"
make "COMPL=$COMPL" "OS=$OS" || {
    echo make failed
    exit 1
}
export MAKEDIR=$CWD/MAKEDIR/$OS

echo
echo "***** Running MakeMake    *****"

bin/$OS/MakeMake > MakeFile EXEC *.[hC] MakeDir MAKEDIR/$OS ECHO=echo || \
{
    echo MakeMake failed
    exit 1
}

CWD=`pwd`
PATH=$CWD/bin/$OS:$PATH
MAKEDIR=$CWD/MAKEDIR/$OS
export PATH MAKEDIR
echo
echo "***** Running make -f MakeFile    *****"
make -f MakeFile  "OS=$OS" "CWD=$CWD" || {
    echo make -f MakeFile failed
    exit 1
}

echo MakeMake passes
